name: Win32/UWP build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        name:            ["Win10"]
        toolset:         ["x64"]
        build_type:      ["Debug", "Release"]
        cmake_generator: ["Visual Studio 17 2022"]
        # Do not build GLSLang and friends to save time as it is built by the Core and Engine CI.
        cmake_args:      [""]
        platform:        ["Win32"]
        build_args:      ["-- -restore"]

    name: Win10 -> ${{ matrix.name }}-${{ matrix.toolset }}, ${{ matrix.build_type }}

    steps:
    - name: Checkout
      uses: DiligentGraphics/github-action/checkout@v1

    - name: Set up build environment
      if:   success()
      uses: DiligentGraphics/github-action/setup-build-env@v1
      with:
        platform:        ${{ matrix.platform }}
        cmake-generator: ${{ matrix.cmake_generator }}
        ninja-vs-arch:   ${{ matrix.toolset }}

    - name: Configure CMake
      if:   success()
      uses: DiligentGraphics/github-action/configure-cmake@v1
      with:
        generator:  ${{ matrix.cmake_generator }}
        vs-arch:    ${{ matrix.toolset }}
        build-type: ${{ matrix.build_type }}
        cmake-args: ${{ matrix.cmake_args }}

    - name: Build
      id:   build
      if:   success()
      uses: DiligentGraphics/github-action/build@v1
      with:
        build-args: ${{ matrix.build_args }}
